# Generated by Django 4.0.5 on 2022-07-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
