# Generated by Django 4.0.5 on 2022-07-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_post_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_edited',
            field=models.BooleanField(default=False),
        ),
    ]
