# Generated by Django 4.0.5 on 2022-07-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_timestamp']},
        ),
    ]
